# source: ./_posts
destination: ./_site
baseurl: "/blog"
future: true
lsi: true
paginate: 3
permalink: pretty
highlighter: pygments
permalink: none
disqusShortname: "tyukiand-blog"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
